In [1]:
import numpy as np

R_imu_from_husky = np.identity(3)
R_imu_from_husky[:,0] = (0,1,0)
R_imu_from_husky[:,1] = (1,0,0)
R_imu_from_husky[:,2] = (0,0,-1)
R_mocap_from_husky = np.identity(3)
R_mocap_from_husky[:,0] = (0,-1,0)
R_mocap_from_husky[:,1] = (1,0,0)
R_mocap_from_husky[:,2] = (0,0,1)

print(R_imu_from_husky, " ", R_mocap_from_husky)

[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]   [[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]


In [1]:
import math
x= 0.00606879
y = 0.01241519
z = 9.80664253

calc = math.sqrt(math.pow(x,2) + math.pow(y,2) + math.pow(z,2))
print(calc)

9.806652266617776


In [44]:
import numpy as np

rot = np.array([-0.99969655,-0.0246262,0.00061895,0.02462696,-0.9996959,0.00126612,0.00058759,0.00128098,0.99999905])
Rot = np.zeros((2,3,3))
for i in range(3):
    Rot[0,i,:] = rot[i:i+3]
print(Rot)

[[[-9.9969655e-01 -2.4626200e-02  6.1895000e-04]
  [-2.4626200e-02  6.1895000e-04  2.4626960e-02]
  [ 6.1895000e-04  2.4626960e-02 -9.9969590e-01]]

 [[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
  [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]]]


In [8]:
import numpy as np
import math

error = np.zeros((7,2))
error[0,:] = (1.00054211, 0.88122736)
error[1,:] = (-1.35823788,  0.43767735)
error[2,:] = (-1.57024445,  1.06794798)
error[3,:] = (1.65672089, 0.69517758)
error[4,:] = (-0.70477557, -3.36006325)
error[5,:] = (-1.30259304, -1.12036853)
error[6,:] = (0.91891269, 2.66977253)
avg_error = 0
error_temp = 0
for i in range(len(error)):
    error_temp = math.sqrt(pow(error[i,0],2)+pow(error[i,1],2))
    avg_error = avg_error + error_temp
    # print(error_temp)

avg_error = avg_error/7

print(avg_error)

2.061536647380643
